### ISSUE TITLE
Error when running modified_export.py script.

### ISSUE THREAD

**Issue by DenisMrGnusa** [spring98/flutter-yolo-realtime-plugin#3]
Hello, 
and thank you for your great plugin.

I have some issue when implement my own .pt file from roboflow.
An error occurred when trying to run the modified_export.py script according to the instructions you wrote in the readme. However, I encountered an error as shown below:

<img width="2560" alt="Screenshot 2023-12-30 at 20 34 37" src="https://github.com/spring98/flutter-yolo-realtime-plugin/assets/34623582/86ae27d1-9f5a-4c98-bf84-1deecf8a96bf">

**Comment by spring98** [comment]
hello!
Thank you for your interest in my plugin.

It seems that the best_yolov5s.pt file is not in the same path as modified_export.py.

If the data was customized and trained, the pt file usually exists here: runs/train/exp/weights/best.pt

--weights runs/train/exp/weights/your_model.pt
Please set the path like this.

**Comment by DenisMrGnusa** [comment]
thank you for your fast reply,
I have managed to fix it, by changing the coremltools version to the same version as the one in your documentation (6.2).

**Comment by jmtrutna** [comment]
> thank you for your fast reply, I have managed to fix it, by changing the coremltools version to the same version as the one in your documentation (6.2).

This worked for me as well.
