### ISSUE TITLE
Yolov8 support 

### ISSUE THREAD

**Issue by GuenKainto** [spring98/flutter-yolo-realtime-plugin#7]
Hello, thanks for this wonderful plugin. I have a small question that does this support Yolov8 models or only Yolov5

**Comment by spring98** [comment]
Thank you for your interest in my plugin.

Currently, only yolov5 has been worked on and tested. Support for yolov8 is also planned in the future.

thank you

**Comment by GuenKainto** [comment]
That's great, I hope it will be supported soon
